### ISSUE TITLE
Ошибка с иконками

### ISSUE THREAD

**Issue by alexeygritsenko** [amatkivskiy/MaterialDrawer-Xamarin#2]
~
Ошибка        Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'android-iconics-1.2.0, Version=1.0.1.0, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
Имя файла: 'android-iconics-1.2.0.dll'
~
Похоже дравер жеско требует именно 1.2 версию, у меня же автоматически поставилась  1.2.1
Попробовал ее снести и откатиться до старой, но опять же ошибка) До конца не удалилась а новая не установилась. Запоролся проект(

**Comment by amatkivskiy** [comment]
@alexeygritsenko 
А какой проект запускаете?

**Comment by amatkivskiy** [comment]
@alexeygritsenko 
Попробуй последний релиз 3.1.2.

**Comment by alexeygritsenko** [comment]
Имел ввиду VS15 физический проект для дроида...
После иконок ничего не хотелось ставиться, как ни странно помогла лишь перезагрузка и создание нового проекта. Ваша версия 3.1.2 удачно стала и скомпилилась с иконками 1.2.1 (хотя в манифесте мин. опять же стоит 1.2.0, а жеско зашит 1.2.1 - не советую так делать в будущем, лучше исключить версии в названиях dll'ok)

**Comment by seredasv** [comment]
снова упала с ошибкой:

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(5,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly.
Xamarin.Android.XamarinAndroidException: error XA2006: Reference to metadata item 'Android.Views.ViewOutlineProvider' 
(defined in 'material-drawer-3.1.2, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') from 'material-drawer-3.1.2, 
Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed 
to resolve Android.Views.ViewOutlineProvider
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
   at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
   at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
   at Mono.Linker.Steps.MarkStep.Initialize()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   --- End of inner exception stack trace ---
   at Xamarin.Android.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() (MSB4018)

Подскажите пожалуйста как исправить

**Comment by amatkivskiy** [comment]
@seredasv
попробуйте скачать library проект и подключить его к своему проекту на прямую

**Comment by amatkivskiy** [comment]
@seredasv
попробуйте ещё 
http://forums.xamarin.com/discussion/24845/linkassemblies-task-failed-unexpectedly

**Comment by seredasv** [comment]
Забыл сказать) спасибо огромное за библиотеку. Я её и на Java и на С# использую. 

Честно говоря я поставил через терминал пакеты и собрал в visual studio и все ок.

**Comment by seredasv** [comment]
все прекрассно!

Вот это помогло - I got this error too, resolved it like this:
Under the project properties-> Android Build->Linker-> Link behavior - set to link all

**Comment by amatkivskiy** [comment]
@alexeygritsenko 
Ок, в следующих релизах заберу номер релиза из названия .dll.

**Comment by amatkivskiy** [comment]
@alexeygritsenko 
@seredasv 
Можно закрывать?

**Comment by seredasv** [comment]
Наверное да. У меня все ок. Уже Билды делал раз 10.
